-- -----------------------------------------------------
--  WARNING
-- By default, this script is using `asp` database name
-- If it's necessary, change it into #17, #22, #23
-- and don't forget to change ['DB_NAME'] into .env file
-- -----------------------------------------------------

-- MySQL Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema asp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `asp` ;

-- -----------------------------------------------------
-- Schema asp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asp` ;
USE `asp` ;

-- -----------------------------------------------------
-- Table `post_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `post_category` ;

CREATE TABLE IF NOT EXISTS `post_category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `isActive` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `post` ;

CREATE TABLE IF NOT EXISTS `post` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `post_category` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`post_id`),
  INDEX `fk_post_post_type_idx` (`post_category` ASC) VISIBLE,
  CONSTRAINT `fk_post_post_type`
    FOREIGN KEY (`post_category`)
    REFERENCES `post_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `post_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `post_image` ;

CREATE TABLE IF NOT EXISTS `post_image` (
  `post_images_id` INT NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(45) NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`post_images_id`),
  INDEX `fk_post_image_post1_idx` (`post_id` ASC) VISIBLE,
  UNIQUE INDEX `image_url_UNIQUE` (`image_url` ASC) VISIBLE,
  CONSTRAINT `fk_post_image_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
