-- MySQL Script generated by MySQL Workbench
-- Tue 11 Oct 2022 02:56:24 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema asp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `asp` ;

-- -----------------------------------------------------
-- Schema asp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asp` ;
USE `asp` ;

-- -----------------------------------------------------
-- Table `asp`.`post_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asp`.`post_category` ;

CREATE TABLE IF NOT EXISTS `asp`.`post_category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asp`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asp`.`post` ;

CREATE TABLE IF NOT EXISTS `asp`.`post` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `post_category` INT NOT NULL,
  `create_time` TIMESTAMP NULL,
  PRIMARY KEY (`post_id`),
  INDEX `fk_post_post_type_idx` (`post_category` ASC) VISIBLE,
  CONSTRAINT `fk_post_post_type`
    FOREIGN KEY (`post_category`)
    REFERENCES `asp`.`post_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asp`.`post_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asp`.`post_image` ;

CREATE TABLE IF NOT EXISTS `asp`.`post_image` (
  `post_images_id` INT NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(45) NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`post_images_id`),
  INDEX `fk_post_image_post1_idx` (`post_id` ASC) VISIBLE,
  UNIQUE INDEX `image_url_UNIQUE` (`image_url` ASC) VISIBLE,
  CONSTRAINT `fk_post_image_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `asp`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
